name: background-service
version: 0.1.0.0
license: BSD3
author: "asimuskov"
maintainer: "opiumofthepeople@yandex.ru"
copyright: "2021 asimuskov"

extra-source-files:
  - README.md
    #  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: TODO

dependencies:
- base >= 4.7 && < 5
- text
- stm
- unliftio-core
- unliftio
- safe-exceptions
- resource-pool

ghc-options:
  - -Wall
  - -Wcompat
  - -Werror=missing-fields
  - -Werror=incomplete-record-updates
  - -Werror=missing-methods
  - -Werror=incomplete-patterns
  - -Wincomplete-uni-patterns
  - -Wpartial-fields

default-extensions:
  - RecordWildCards
  - NamedFieldPuns
  - DuplicateRecordFields
  - OverloadedLabels
  - OverloadedStrings
  - FlexibleContexts
  - FlexibleInstances
  - StandaloneDeriving
  - ScopedTypeVariables
  - ExplicitForAll
  - TypeOperators
  - TypeApplications
  - DeriveGeneric
  - MonoLocalBinds
  - DerivingStrategies
  - BlockArguments
  - PostfixOperators
  - TupleSections
  - LambdaCase
  - NumericUnderscores
  - MultiWayIf
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DerivingVia
  - EmptyDataDecls
  - ExistentialQuantification
  - FunctionalDependencies
  - GADTs
  - KindSignatures
  - MultiParamTypeClasses
  - NumDecimals
  - PatternSynonyms
  - RankNTypes
  - TypeFamilies
  - ViewPatterns
  - PartialTypeSignatures

library:
  source-dirs: src

